### ISSUE TITLE
Feat: working on Home page Design

### ISSUE THREAD

**Issue by amuza2** [devunionorg/PetFinderMAUI#22]
Working on home page where the user will be redirected when he logs in

**Comment by amuza2** [comment]
where is the bug? the is not created yet, no code yet!!! @abdelillahbel  why there is Bug label?

**Comment by abdelillahbel** [comment]
* I am working on this issue by fixing general app bug's and impl of dashboard on home page @amuza2

**Comment by amuza2** [comment]
> * I am working on this issue by fixing general app bug's and impl of dashboard on home page @amuza2
You have to create another issue for Imp, not this one, imp features must be separated by several issues, an issue must deal or fix only one thing.
don't take and write on this issue as it's purpose is different of what you are doing
@abdelillahbel

**Comment by abdelillahbel** [comment]
##### I am done with this @amuza2 #51 #52 #53
